import fs from 'node:fs';
import path from 'node:path';
import { defineConfig, type Plugin } from 'vite';
import mkcert from 'vite-plugin-mkcert';

/**
 * Vite plugin that serves the WebTransport certificate hash generated by the
 * Rust server. The file lives at `../certs/cert-hash.json` and is read fresh
 * on every request so the client always picks up the latest hash.
 */
function certHashPlugin(): Plugin {
  const certsDir = path.resolve(__dirname, '../certs');

  return {
    name: 'serve-cert-hash',
    configureServer(server) {
      server.middlewares.use('/cert-hash.json', (_req, res) => {
        const filePath = path.join(certsDir, 'cert-hash.json');

        if (fs.existsSync(filePath)) {
          res.setHeader('Content-Type', 'application/json');
          res.setHeader('Cache-Control', 'no-store');
          res.end(fs.readFileSync(filePath, 'utf-8'));
        } else {
          res.statusCode = 404;
          res.end(
            JSON.stringify({
              error: 'cert-hash.json not found. Start the Rust server first to generate certificates.',
            }),
          );
        }
      });
    },
  };
}

export default defineConfig({
  plugins: [
    mkcert({
      savePath: './certs',
      certFileName: 'localhost.pem',
      keyFileName: 'localhost-key.pem',
      hosts: ['localhost', '127.0.0.1', '::1'],
    }),
    certHashPlugin(),
  ],
});
